name: Changelog Automation

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
  pull_request:
    types:
      - closed

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Existing 'update-changelog' Branch
        run: |
          git fetch origin update-changelog || echo "Branch does not exist yet."

      - name: Create or Checkout 'update-changelog' Branch
        run: |
          if git rev-parse --verify origin/update-changelog; then
            git checkout update-changelog
            git pull origin update-changelog
          else
            git checkout -b update-changelog
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install git-changelog
        run: pip install git-changelog

      - name: Update Changelog
        run: git-changelog > CHANGELOG.md

      - name: Commit Changelog Updates
        run: |
          git add CHANGELOG.md
          git commit -m "Update Changelog [skip ci]" || echo "No changes to commit"
          git push origin update-changelog

      - name: Create or Update Pull Request
        id: create_pull_request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-changelog
          title: "Update Changelog"
          body: |
            This pull request updates the changelog with the latest changes.
            Previous history has been preserved in the `update-changelog` branch.
