name: Weekly Changelog Release

on:
  workflow_dispatch:
 
  schedule:
    - cron: "0 12 * * 5" # Every Friday at noon (UTC)

permissions:
  contents: write

jobs:
  generate-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Generate Weekly Changelog
        run: |
          # Get the start of the week (last Monday) and the end of the week (last Sunday)
          START_DATE=$(date -d "last monday" +%Y-%m-%d)
          END_DATE=$(date -d "last sunday" +%Y-%m-%d)
          
          echo "# Changelog for ${START_DATE} to ${END_DATE}" > CHANGELOG.md
          echo "\n## Changes" >> CHANGELOG.md
          
          # Log commits made during the week
          git log --since="$START_DATE" --until="$END_DATE" --pretty=format:"- %s (%an)" >> CHANGELOG.md

          # Check if there are any changes
          if grep -q "-" CHANGELOG.md; then
            echo "Changes found. Preparing release."
          else
            echo "No changes this week. Skipping release."
            exit 0
          fi

      - name: Commit Changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Weekly Changelog: ${START_DATE} to ${END_DATE} [skip ci]" || echo "No changes to commit"
          git push origin HEAD

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use the changelog as the release body
          TAG="weekly-changelog-${START_DATE}"
          RELEASE_TITLE="Weekly Changelog: ${START_DATE} to ${END_DATE}"
          BODY=$(cat CHANGELOG.md)
          
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg tag $TAG --arg title "$RELEASE_TITLE" --arg body "$BODY" \
              '{ tag_name: $tag, name: $title, body: $body, draft: false, prerelease: false }')" \
            https://api.github.com/repos/${{ github.repository }}/releases
