name: Weekly Changelog Release

on:
  workflow_dispatch:  # Allows manual execution
  schedule:
    - cron: "0 14 * * 5"  # Runs every Friday at 14:00 UTC (15:00 CET/CEST)

permissions:
  contents: write

jobs:
  generate-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate changelog

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install git-changelog
        run: pip install git-changelog

      - name: Generate Weekly Changelog
        run: |
          # Calculate the start (previous Friday) and end date (current Friday)
          END_DATE=$(date -u +"%Y-%m-%d") # Current date (Friday)
          START_DATE=$(date -u -d "$END_DATE - 7 days" +"%Y-%m-%d") # Previous Friday

          echo "Generating changelog from $START_DATE to $END_DATE"

          # Generate changelog for the past week
          git-changelog --since "$START_DATE" --until "$END_DATE" --output CHANGELOG.md

          # Check if there are actual changes
          if grep -q "-" CHANGELOG.md; then
            echo "Changelog generated successfully."
          else
            echo "No changes this week. Skipping release."
            exit 0
          fi

      - name: Commit and Push Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add CHANGELOG.md
          
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping push."
            exit 0
          fi
          
          git commit -m "Weekly Changelog: ${START_DATE} to ${END_DATE} [skip ci]"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Create GitHub Release (Draft)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a tag and release title
          TAG="weekly-changelog-${END_DATE}"
          RELEASE_TITLE="Weekly Changelog: ${START_DATE} to ${END_DATE}"
          BODY=$(cat CHANGELOG.md)
          
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg tag "$TAG" --arg title "$RELEASE_TITLE" --arg body "$BODY" \
              '{ tag_name: $tag, name: $title, body: $body, draft: true, prerelease: false }')" \
            https://api.github.com/repos/${{ github.repository }}/releases
