name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Step 3: Install MkDocs and dependencies
      - name: Install MkDocs
        run: |
          pip install mkdocs-material

      # Step 4: Build the MkDocs site
      - name: Build MkDocs
        run: mkdocs build --clean

      # Step 5: Deploy to GitHub Pages (Manual Deployment)
      - name: Deploy to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git checkout -b docs-gh-pages
          cp -r site/* .
          git add .
          git commit -m "Deploy MkDocs site"
          git push --force origin gh-pages
